import { Equipment, MuscleGroup } from '../../services/database';

export const MUSCLE_GROUP_LABEL_ES: Record<MuscleGroup, string> = {
	Chest: "Pecho",
	Shoulders: "Hombros",
	Triceps: "Tríceps",
	Back: "Espalda",
	Biceps: "Bíceps",
	Forearms: "Antebrazos",
	Cuadriceps: "Cuádriceps",
	Hamstrings: "Isquios",
	Gluts: "Glúteos",
	Calves: "Gemelos",
	Abductors: "Abductores",
	Adductors: "Aductores",
	Abs: "Abdominales",
};

export const getMuscleGroupLabelEs = (group: MuscleGroup): string =>
  MUSCLE_GROUP_LABEL_ES[group] ?? group;

export const EQUIPMENT_LABEL_ES: Record<Equipment, string> = {
	BARBELL: "Barra",
	DUMBBELL: "Mancuerna",
	BODYWEIGHT: "Peso corporal",
	CABLE: "Cable",
	MACHINE: "Máquina",
	SMITH: "Smith"
};

export const getEquipmentLabelEs = (equipment: Equipment): string => EQUIPMENT_LABEL_ES[equipment] ?? equipment;

export const getExerciseNameEs = (code: string, fallback?: string) =>
  EXERCISE_NAME_ES[code] ?? fallback ?? code;

export const EXERCISE_NAME_ES: Record<string, string> = {
  'close-grip-lat-pulldown': 'Jalón al pecho con agarre cerrado',
  'bayesian-cable-curl': 'Curl de bíceps en polea (Bayesian)',
  'ez-bar-curl': 'Curl de bíceps con barra Z',
  'chest-supported-row': 'Remo con pecho apoyado',
  'cable-row': 'Remo sentado con agarre cerrado',
  'preacher-hammer-curl': 'Curl martillo en banco Scott',
  'cross-body-lat-pullaround': 'Pull-around de dorsales',
  'wide-grip-lat-pulldown': 'Jalón al pecho con agarre amplio',
  '1-arm-dumbbell-row': 'Remo con mancuerna a 1 brazo',
  'standing-hammer-curl': 'Curl martillo de pie',
  'pull-ups': 'Dominadas con agarre amplio',

  'bench-press': 'Press plano con barra',
  'cable-lateral-raise': 'Elevaciones laterales en polea',
  'standing-dumbbell-lateral-raise': 'Elevaciones laterales con mancuernas',
  'incline-bench-press': 'Press inclinado con barra',
  'triceps-pressdown-bar': 'Extensión de tríceps en polea (barra)',
  'overhead-cable-triceps-extension': 'Extensión de tríceps por encima de la cabeza en polea',
  'pec-deck': 'Aperturas en máquina (Pec Deck)',
  'cable-triceps-kickback': 'Patada de tríceps en polea',
  'machine-chest-press': 'Press plano en máquina',
  'smith-flat-bench-press': 'Press plano en máquina Smith',
  'smith-incline-bench-press': 'Press inclinado en máquina Smith',
  'flat-dumbbell-press': 'Press plano con mancuernas',
  'incline-dumbbell-press': 'Press inclinado con mancuernas',
  'smith-machine-jm-press': 'JM press en máquina Smith',
  'push-ups': 'Flexiones de brazos',

  'seated-leg-curl': 'Curl femoral sentado',
  'lying-leg-curl': 'Curl femoral tumbado',
  'leg-press': 'Prensa de piernas',
  'leg-extension': 'Extensión de cuádriceps en máquina',
  'machine-leg-press': 'Prensa de piernas en máquina',
  'hip-adduction': 'Aductores en máquina',
  'standing-calf-raise': 'Elevación de talones en máqina',
  'seated-calf-raise': 'Elevación de talones sentado',
  'lever-standing-calf-raise': 'Elevación de talones de pie',

  'lever-seated-crunch': 'Crunch abdominal en máquina sentado',
  'straight-leg-raise': 'Elevación de piernas estiradas',
  'cable-crunch': 'Crunch abdominal en polea',

  'bent-over-row': 'Remo con barra inclinado',
  'cable-standing-lat-pushdown': 'Pulldown de dorsales de pie en polea',
  'shrug': 'Encogimientos de hombros',
  'lever-lying-t-bar-row': 'Remo en T tumbado en máquina',
  'assisted-pull-ups': 'Dominadas asistidas',
  '45-degree-hyperextension': 'Hipertensiones 45° (espalda baja)',
  'seated-wide-grip-row': 'Remo sentado con agarre amplio',
  'lever-front-pulldown': 'Jalón al pecho en máquina',
  'cable-wide-neutral-grip-pulldown': 'Jalón al pecho con agarre neutro',
  'lever-bent-over-row': 'Remo inclinado barra apoyada',
  'incline-dumbbell-row': 'Remo con mancuernas en banco inclinado',

  'biceps-curl': 'Curl de bíceps de pie',
  'dumbbell-incline-curl': 'Curl de bíceps inclinado con mancuernas',
  'lever-preacher-curl': 'Curl de bíceps en máquina Scott',
  'cable-biceps-curl': 'Curl de bíceps en polea',
  'barbell-preacher-curl': 'Curl de bíceps con barra en banco Scott',
  'dumbbell-preacher-curl': 'Curl de bíceps con mancuerna en banco Scott',
  'concentration-curl': 'Curl de bíceps concentrado',

  'lever-seated-fly': 'Aperturas en máquina',
  'dumbbell-shoulder-press': 'Press de hombros con mancuernas',
  'machine-shoulder-press': 'Press de hombros en máquina',
  'lever-seated-reverse-fly': 'Vuelos posteriores en máquina sentado',
  'front-raise': 'Elevaciones frontales',
  'barbell-shoulder-press': 'Press militar con barra',
  'lever-lateral-raise': 'Elevaciones laterales en máquina',
  'cable-face-pull': 'Face pull en polea',
  'smith-shoulder-press': 'Press de hombros en máquina Smith',
  'cross-over-reverse-fly': 'Vuelos posteriores en polea',

  'cable-standing-fly': 'Aperturas en polea alta',
  'chest-dip': 'Fondos para pecho',
  'fly': 'Aperturas con mancuernas',
  'incline-fly': 'Aperturas inclinadas con mancuernas',
  'cable-middle-fly': 'Aperturas en polea media',
  'cable-seated-chest-fly': 'Aperturas en polea sentado',

  'pulley-overhead-tricep-extension': 'Extensión de tríceps inclinado en polea',
  'lever-seated-dip': 'Fondos en máquina sentado',
  'seated-bench-extension': 'Extensión de tríceps sentado en banco',
  'triceps-dip': 'Fondos para tríceps',
  'assisted-triceps-dip': 'Fondos para tríceps asistidos',

  'deadlift': 'Peso muerto convencional',
  'romanian-deadlift': 'Peso muerto rumano',
  'good-morning': 'Buenos días con barra',

  'barbell-squat': 'Sentadilla con barra',
  'hack-squat': 'Sentadilla hack',
  'smith-squat': 'Sentadilla en máquina Smith',
  'dumbbell-bulgarian-split-squat': 'Sentadilla búlgara con mancuernas',
  'dumbbell-squat': 'Sentadilla con mancuernas',
  'dumbbell-lunges': 'Zancadas con mancuernas',
  'kettlebell-goblet-squat': 'Sentadilla goblet con mancuerna',
  'smith-bulgarian-split-squat': 'Sentadilla búlgara en máquina Smith',
  'smith-lunges': 'Zancadas en máquina Smith',

  'hip-abduction': 'Abductores en máquina',
  'hip-thrust': 'Hip thrust con barra',
  'smith-hip-thrust': 'Hip thrust en máquina Smith',

  'cable-pushdown-rope': 'Extensión de tríceps en polea (soga)',
  'barbell-skullcrusher': 'Press francés con barra (skullcrusher)',
  'dumbbell-skullcrusher': 'Press francés con mancuernas (skullcrusher)',

  'alternate-triceps-extension': 'Extensión alternada de tríceps',
  'assisted-chest-dip': 'Fondos para pecho asistidos',
  'assisted-chin-up': 'Dominadas supinas asistidas',
  'assisted-standing-pul-up': 'Dominadas asistidas de pie en máquina',
  'barbell-bulgarian-split-squat': 'Sentadilla búlgara con barra',
  'barbell-decline-bench-press': 'Press declinado con barra',
  'barbell-front-squat': 'Sentadilla frontal con barra',
  'barbell-lunge': 'Zancadas con barra',
  'barbell-lying-row-rack': 'Remo con barra tumbado sobre rack',
  'barbell-one-arm-bent-over-row': 'Remo inclinado a un brazo con barra',
  'barbell-seated-military-press': 'Press militar sentado con barra',
  'barbell-step-up': 'Step-up con barra',
  'barbell-shrug': 'Encogimientos de hombros con barra',
  'bench-dip': 'Fondos en banco para tríceps',
  'bodyweight-squat': 'Sentadilla con peso corporal',
  'cable-chest-press': 'Press de pecho en polea',
  'cable-donkey-kickback': 'Patada de glúteo en polea (donkey kick)',
  'cable-hip-abduction': 'Abducción de cadera en polea',
  'cable-hip-adduction': 'Aducción de cadera en polea',

  'cable-kneeling-one-arm-lat-pulldown': 'Jalón unilateral de dorsales en polea de rodillas',
  'cable-low-fly': 'Aperturas en polea baja',
  'cable-seated-chest-press': 'Press de pecho sentado en polea',
  'cable-shrug': 'Encogimientos de hombros en polea',
  'cable-single-arm-high-row-chest-support': 'Remo alto unilateral en polea con pecho apoyado',
  'cable-standing-high-cross-triceps-extension': 'Extensión de tríceps alta cruzada en polea',
  'chin-up': 'Dominadas supinas',
  'decline-dumbell-bench-press': 'Press declinado con mancuernas',
  'decline-push-ups': 'Flexiones declinadas',
  'decline-smith-bench-press': 'Press declinado en máquina Smith',
  'diamond-push-up': 'Flexiones diamante',
  'donkey-calf-raise': 'Elevación de talones tipo burro',
  'dumbbell-incline-lateral-raise': 'Elevaciones laterales inclinadas con mancuernas',
  'dumbbell-incline-one-arm-lateral-raise': 'Elevación lateral inclinada a un brazo con mancuerna',
  'dumbbell-kickback': 'Patada de tríceps con mancuerna',
  'dumbbell-one-arm-seated-extension': 'Extensión de tríceps sentado a un brazo con mancuerna',
  'dumbbell-rear-delt-fly': 'Aperturas posteriores con mancuernas',
  'dumbbell-reverse-spider-curl': 'Curl spider con mancuernas',
  'dumbbell-romanian-deadlift': 'Peso muerto rumano con mancuernas',
  'dumbbell-seated-bent-over-reardelt-row': 'Remo posterior sentado inclinado con mancuernas',

  'dumbbell-standing-one-arm-extension': 'Extensión de tríceps de pie a un brazo con mancuerna',
  'dumbbell-standing-triceps-extension': 'Extensión de tríceps de pie con mancuerna',
  'dumbbell-step-up': 'Step-up con mancuernas',
  'dumbbell-zottman-preacher-curl': 'Curl de bíceps en banco inclinado de pie',
  'dumbell-bent-over-row': 'Remo inclinado con mancuernas',
  'dumbell-bent-over-row-chest-support': 'Remo inclinado con mancuernas con pecho apoyado',
  'dumbell-lying-row-rack': 'Remo tumbado con mancuernas sobre banco/rack',
  'dumbell-pull-over': 'Pull-over con mancuerna',
  'elbow-dips': 'Fondos en banco para tríceps',
  'ez-bar-seated-triceps-extension': 'Extensión de tríceps sentado con barra Z',
  'ez-barbell-spider-curl': 'Curl spider con barra Z',
  'flat-plate-loaded-chest-press': 'Press plano en máquina con discos',
  'hip-thrust-machine': 'Hip thrust en máquina',
  'incline-plate-loaded-chest-press': 'Press inclinado en máquina con discos',
  'incline-push-up': 'Flexiones inclinadas',
  'inverted-row': 'Remo invertido',
  'knees-push-up': 'Flexiones apoyando rodillas',
  'landmine-kneeling-squeeze-press': 'Press de rodillas (squeeze press)',
  'landmine-one-arm-bent-over-row': 'Remo inclinado a un brazo con landmine',
  'lever-hip-extension': 'Extensión de cadera en máquina',

  'lever-kneeling-leg-curl': 'Curl femoral de rodillas en máquina',
  'lever-one-leg-extension': 'Extensión de cuádriceps unilateral en máquina',
  'lever-side-hip-abduction': 'Abducción de cadera lateral en máquina',
  'lever-side-hip-adduction': 'Aducción de cadera lateral en máquina',
  'lever-standing-rear-kick': 'Patada posterior de glúteo en máquina',
  'lever-triceps-extension-machine': 'Extensión de tríceps en máquina',
  'machine-back-extension': 'Extensión lumbar en máquina',
  'machine-biceps-curl': 'Curl de bíceps en máquina',
  'machine-calf-raise': 'Elevación de talones en máquina',
  'machine-close-grip-row': 'Remo en máquina con discos',
  'machine-donkey-kickback': 'Patada de glúteo en máquina (donkey kick)',
  'machine-front-lat-pulldown': 'Jalón al frente en máquina',
  'machine-incline-chest-press': 'Press inclinado en máquina',
  'machine-incline-fly': 'Aperturas inclinadas en máquina',
  'machine-lever-high-row': 'Jalón frontal en máquina con discos',
  'machine-lever-pullover': 'Pull-over en máquina',
  'machine-lever-reverse-grip-pulldown': 'Jalón frontal agarre inverso con discos',
  'machine-lever-triceps-extension': 'Extensión de tríceps en máquina',
  'machine-seated-lever-lateral-raise': 'Elevaciones laterales sentado en máquina',
  'machine-shrug': 'Encogimientos de hombros en máquina',

  'muscle-up': 'Muscle-up en barra',
  'neutral-grip-cable-row': 'Remo en polea con agarre neutro',
  'neutral-pull-up': 'Dominadas con agarre neutro',
  'one-arm-side-triceps-pushdown': 'Extensión de tríceps lateral a un brazo en polea',
  'overhead-rope-triceps-extension': 'Extensión de tríceps por encima de la cabeza con soga',
  'plate-loaded-triceps-dip': 'Fondos de tríceps en máquina con discos',
  'reverse-grip-lat-pulldown': 'Jalón al pecho con agarre inverso',
  'reverse-vertical-hack-squat': 'Sentadilla hack vertical invertida',
  'seated-full-crunch': 'Crunch abdominal completo en máquina sentado',
  'single-leg-squat': 'Sentadilla a una pierna',
  'smith-back-shurg': 'Encogimientos de hombros en máquina Smith',
  'smith-bent-over-row': 'Remo plano en máquina Smith',
  'smith-calf-raise': 'Elevación de talones en máquina Smith',
  'smith-dead-lift': 'Peso muerto en máquina Smith',
  'smith-front-squat': 'Sentadilla frontal en máquina Smith',
  'smith-hex-press': 'Hex press en máquina Smith',
  'smith-incline-row': 'Remo inclinado en máquina Smith',
  'smith-leg-press': 'Prensa de piernas en máquina Smith',
  'smith-romanian-deadlift': 'Peso muerto rumano en máquina Smith',
  'smith-shrug': 'Encogimientos de hombros en máquina Smith',

  'suspended-row': 'Remo suspendido (TRX/anillas)',
  'triceps-triangle-pushdown': 'Extensión de tríceps en polea con barra triángulo',
  'walking-lunge': 'Zancadas caminando',
  'weighted-chin-up': 'Dominadas supinas lastradas',
  'weighted-neutral-pull-up': 'Dominadas con agarre neutro lastradas',
  'weighted-pull-up': 'Dominadas lastradas',
  'weighted-tricep-dip': 'Fondos de tríceps lastrados',
};