import { StyleSheet } from 'react-native';

export const editStyles = StyleSheet.create({
	screen: { flex: 1, backgroundColor: '#fff' },
  header: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 8, alignItems: 'center' },
  title: { fontSize: 20, fontWeight: '800', color: '#111827' },
  subtitle: { fontSize: 16, fontWeight: '600', color: '#374151', marginTop: 4 },

  list: { padding: 16, paddingBottom: 24 },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    marginBottom: 12,
    shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  exerciseName: { fontSize: 16, fontWeight: '700', color: '#111827', flex: 1, marginRight: 10 },
  actionsRow: { flexDirection: 'row', gap: 8 },
  iconBtn: { padding: 6, borderRadius: 8, backgroundColor: '#F3F4F6' },

  pillWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
  },
  pill: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: '#F3F4F6' },
  pillText: { fontSize: 13, color: '#111827', fontWeight: '600' },
  emptyPillText: { color: '#6B7280', fontSize: 13 },

  addBtn: {
    height: 46, borderRadius: 10, backgroundColor: '#007AFF',
    alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8,
    marginTop: 6,
  },
  addBtnText: { color: '#fff', fontWeight: '800' },

  // Modal (mismos nombres que tu modal original)
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center' },
  modalContainer: { width: '85%', backgroundColor: '#fff', borderRadius: 12, padding: 20 },
  modalTitle: { fontSize: 18, fontWeight: '700', textAlign: 'center', marginBottom: 16 },
  fieldRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  fieldInput: { flex: 1, borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, marginHorizontal: 4 },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  checkboxBox: { width: 20, height: 20, borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 4, marginRight: 8, justifyContent: 'center', alignItems: 'center' },
  checkboxChecked: { width: 12, height: 12, backgroundColor: '#007AFF', borderRadius: 2 },
  checkboxLabel: { fontSize: 16, color: '#333' },
  buttonsRow: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 12 },
  addSetButton: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#007AFF20', borderRadius: 8 },
  addSetButtonDisabled: { backgroundColor: '#E5E7EB' },
  addSetText: { fontSize: 16, color: '#007AFF', fontWeight: '700' },
  cancelButton: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 8, paddingVertical: 12, alignItems: 'center', marginTop: 8 },
  cancelButtonText: { color: '#374151', fontWeight: '700', fontSize: 16 },
  modalButton: { backgroundColor: '#007AFF', paddingVertical: 12, borderRadius: 8, alignItems: 'center', marginTop: 8 },
  modalButtonDisabled: { backgroundColor: '#9CA3AF' },
  modalButtonText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  modalButtonTextDisabled: { color: '#E5E7EB' },
});

export const addStyles = StyleSheet.create({
	  screen: { flex: 1, backgroundColor: '#fff' },
  headerTitle: { fontSize: 18, fontWeight: '800', textAlign: 'center', marginTop: 16, marginBottom: 8 },
  list: { padding: 16 },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1, borderColor: '#E5E7EB',
    padding: 12,
    marginBottom: 12,
    alignItems: 'center',
    shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2,
  },
  image: { width: 100, height: 100, marginBottom: 8, resizeMode: 'contain' },
  cardText: { fontSize: 15, fontWeight: '700', textAlign: 'center' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center' },
  modalContainer: { width: '85%', backgroundColor: '#fff', borderRadius: 12, padding: 20 },
  modalTitle: { fontSize: 18, fontWeight: '700', textAlign: 'center', marginBottom: 16 },
  fieldRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  fieldInput: { flex: 1, borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, marginHorizontal: 4 },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  checkboxBox: { width: 20, height: 20, borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 4, marginRight: 8, justifyContent: 'center', alignItems: 'center' },
  checkboxChecked: { width: 12, height: 12, backgroundColor: '#007AFF', borderRadius: 2 },
  checkboxLabel: { fontSize: 16, color: '#333' },
  buttonsRow: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 12 },
  addSetButton: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#007AFF20', borderRadius: 8 },
  addSetButtonDisabled: { backgroundColor: '#E5E7EB' },
  addSetText: { fontSize: 16, color: '#007AFF', fontWeight: '700' },
  cancelButton: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 8, paddingVertical: 12, alignItems: 'center', marginTop: 8 },
  cancelButtonText: { color: '#374151', fontWeight: '700', fontSize: 16 },
  modalButton: { backgroundColor: '#007AFF', paddingVertical: 12, borderRadius: 8, alignItems: 'center', marginTop: 8 },
  modalButtonDisabled: { backgroundColor: '#9CA3AF' },
  modalButtonText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  modalButtonTextDisabled: { color: '#E5E7EB' },
});

export const imgStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  sheet: {
    width: '100%',
    maxWidth: 480,
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingTop: 36,
    paddingBottom: 12,
    paddingHorizontal: 12,
  },
  closeBtn: {
    position: 'absolute',
    top: 6,
    right: 8,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeText: { fontSize: 16, fontWeight: '700', color: '#333' },
  imgWrap: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#f6f6f6',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  placeholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderText: { color: '#888', fontWeight: '600' },
  caption: {
    textAlign: 'center',
    marginTop: 10,
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    paddingHorizontal: 8,
  },
});